import { SampleAttackScenario } from '../types';

export const SAMPLE_SCENARIOS: SampleAttackScenario[] = [
  {
    id: 'parking_meter_quish',
    title: 'City Parking Meter Sticker Scam',
    tag: 'Physical Tampering',
    category: 'Urgent Payment Scam',
    context: 'Physical counterfeit vinyl sticker affixed over the official city pay station QR code.',
    url: 'http://city-parking-pay.top/meter/pay-fine?meterId=4921&urgent=true&penalty=overdue',
    expectedVerdict: 'critical',
    physicalVector: 'Vinyl Sticker Overlay',
    description: 'Attackers print identical looking vinyl decals and stick them directly over parking meter glass. The link routes to an unencrypted .top domain harvesting credit cards under the threat of immediate vehicle towing.',
  },
  {
    id: 'usps_package_notice',
    title: 'Counterfeit Delivery Notice Slip',
    tag: 'Lookalike Domain',
    category: 'Package Redelivery Fraud',
    context: 'Fake yellow missed-package slip placed on front doors with an urgent QR code to pay a redelivery fee.',
    url: 'https://usps-redelivery-package.xyz/auth/verify?tracking=940011189922&action=card',
    expectedVerdict: 'critical',
    physicalVector: 'Door Hanger / Mailed Slip',
    description: 'Mimics the United States Postal Service brand identity, hosting the form on a high-churn .xyz domain designed to harvest full billing addresses and card CVVs.',
  },
  {
    id: 'restaurant_bill_ip',
    title: 'Rogue Restaurant Table QR',
    tag: 'Raw IP Host',
    category: 'Direct Card Skimmer',
    context: 'Adhesive QR code stuck to corner cafe tables claiming "Scan here for 15% off bill & instant mobile checkout".',
    url: 'http://185.220.101.5:8080/checkout/table-pay?session=9201&cvv=verify',
    expectedVerdict: 'critical',
    physicalVector: 'Table Tent / Acrylic Menu Sticker',
    description: 'Bypasses DNS entirely to route through a bulletproof Russian/European VPS IP address over unencrypted HTTP with non-standard port 8080.',
  },
  {
    id: 'bitly_cloaked_promo',
    title: 'Cloaked Parking / Transit Discount',
    tag: 'Opaque Redirect',
    category: 'URL Cloaking',
    context: 'Sticker at bus transit shelter advertising "Free commuter ride vouchers — scan now".',
    url: 'https://bit.ly/transit-free-pass-claim-2026',
    expectedVerdict: 'suspicious',
    physicalVector: 'Subway / Bus Stop Poster',
    description: 'Uses an opaque URL shortener to hide the eventual destination from phone camera preview popups, masking deceptive affiliate funnels.',
  },
  {
    id: 'safe_sweetgreen_menu',
    title: 'Verified Sweetgreen Digital Menu',
    tag: 'Legitimate',
    category: 'Standard Restaurant Menu',
    context: 'Official dine-in QR code printed inside laminated table booklet at a legitimate restaurant.',
    url: 'https://menu.sweetgreen.com/order/locations/soho-spring-st',
    expectedVerdict: 'safe',
    physicalVector: 'Official Laminated Table Card',
    description: 'Authentic high-reputation domain utilizing valid TLS certificates, standard naming structure, and no deceptive parameter patterns.',
  },
  {
    id: 'safe_mta_transit',
    title: 'Official NYC MTA Subway Timetable',
    tag: 'Legitimate',
    category: 'Public Municipal Transit',
    context: 'Permanent etched stainless steel QR plate mounted on station platform pillars.',
    url: 'https://mta.info/schedules/subway/line-1-uptown',
    expectedVerdict: 'safe',
    physicalVector: 'Municipal Infrastructure Mount',
    description: 'Direct link to state municipal transit authority. Complies with clean domain guidelines and zero obfuscation.',
  }
];
